apiVersion: v1
kind: Service
metadata:
  name: aedifex-app
spec:
  type: NodePort
  selector:
    app: aedifex-app
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aedifex-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aedifex-app
  template:
    metadata:
      labels:
        app: aedifex-app
    spec:
      containers:
        - name: aedifex-app
          image: 824987503353.dkr.ecr.us-west-2.amazonaws.com/harness:104
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: BUILD_ID
              value: "3.9"
